### ISSUE TITLE
Vim 7.4 :new file.h places cursor outbox

### ISSUE THREAD

**Issue by sundoctor** [thinca/vim-template#1]
When I start vim and than start new buffer
:new file.h
template from /template/template.h cursor is on top - not in <+CURSOR+>

**Comment by thinca** [comment]
Please tell me your settings(vimrc).

**Comment by sundoctor** [comment]
nnoremap &lt;esc&gt; :noh&lt;return&gt;&lt;esc&gt;
set noerrorbells visualbell t_vb=
set guifont=Terminus\ 8
set statusline=%F%m%r%h%w\ [FORMAT=%{&amp;ff}]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v]\ [%p%%]\ [LEN=%L]
set laststatus=2
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
highlight lCursor guifg=NONE guibg=Cyan
set foldenable
set foldmethod=manual
set foldcolumn=3
set foldlevel=1
syntax on
filetype indent on
filetype plugin on
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nu
&quot;set winheight=999
set cursorline
set ic
set hls
set expandtab
au FileType crontab,fstab,make set noexpandtab tabstop=8 shiftwidth=8
set showcmd
set showmode
set ruler
set showmatch
set dir=~/.vim
set hidden
set listchars=tab:&#183;&#183;
set list
set encoding=utf-8
set t_Co=256

function InsertTabWrapper()
     let col = col(&#39;.&#39;) - 1
     if !col || getline(&#39;.&#39;)[col - 1] !~ &#39;\k&#39;
         return &quot;&quot;
     else
         return &quot;&lt;c-p&gt;&quot;
     endif
endfunction
imap &lt;tab&gt; &lt;c-r&gt;=InsertTabWrapper()&lt;cr&gt;
set complete=&quot;&quot;
set complete+=.
set complete+=k
set complete+=b
set complete+=t

let Tlist_Show_One_File = 1
let NERDTreeHijackNetrw = 0
let NERDTreeShowBookmarks = 1
let NERDTreeHijackNetrw = 0
let NERDTreeShowBookmarks = 1
let g:session_autosave = &#39;no&#39;
let g:session_autoload = &#39;no&#39;
map &lt;C-h&gt; &lt;Esc&gt;:bp&lt;CR&gt;
imap &lt;C-h&gt; &lt;Esc&gt;:bp&lt;CR&gt;
map &lt;C-l&gt; &lt;Esc&gt;:bn&lt;CR&gt;
imap &lt;C-l&gt; &lt;Esc&gt;:bn&lt;CR&gt;
map &lt;C-k&gt; &lt;Esc&gt;:bdelete&lt;CR&gt;
imap &lt;C-k&gt; &lt;Esc&gt;:bdelete&lt;CR&gt;
map &lt;F2&gt; &lt;Esc&gt;:NERDTreeToggle&lt;CR&gt;
map &lt;F3&gt; &lt;Esc&gt;:TlistToggle&lt;CR&gt;
map &lt;F4&gt; &lt;Esc&gt;:CtrlPBuffer&lt;CR&gt;
map &lt;F5&gt; &lt;Esc&gt;:CtrlPTag&lt;CR&gt;
map &lt;F6&gt; &lt;Esc&gt;:BufExplorer&lt;CR&gt;
set wildmenu
set wcm=&lt;Tab&gt;
menu Exec.quit    :wqa!
menu Exec.bash    :!export TERM=rxvt-unicode-256color &amp;&amp; /bin/bash&lt;CR&gt;
menu Exec.mc      :!mc&lt;CR&gt;
map &lt;C-m&gt; :emenu Exec.&lt;Tab&gt;

**Comment by thinca** [comment]
You have to write a setting.
The example of `<+CURSOR+>` is [here](https://github.com/thinca/vim-template/blob/24687c1a59cb2828be4aec21ec75103d22a1c71e/doc/template.txt#L126-L129).
See `:help template-command-execution` for more information.

**Comment by sundoctor** [comment]
Thank you. I'll try it
