### ISSUE TITLE
テンプレートファイルの1行目1桁目に半角コロン（:）があるとテンプレートを使った新規作成時にエラー

### ISSUE THREAD

**Issue by lamsh** [thinca/vim-template#3]
例えば、以下の内容のWIndowsのバッチファイルのテンプレートファイルを`~/.vim/template/template.bat`に配置します。

```
:: \file template.bat
```

`::`はコメントアウト`REM`と同じ意味の構文です。
この状態で`vim a.bat`で`template.bat`をベースにしてファイルを新規作成しようとすると以下のエラーが出ます。

```
Error detected while processing function template#load:
line 56:
Vim:E10: \ should be followed by /, ? or &
```

他のファイルでも試したところテンプレートファイルの1行目1桁目にコロン（`:`）があるとダメなようです。2行目や1行目2桁目に`:`がある場合はエラーはおきませんでした。
例えば、以下の最小限のテンプレートファイル~/.vim/template/template.hogeでも問題は再現します。

```
:
```

`vim a.hoge`を実行すると以下のエラーが出ます。

```
Error detected while processing function template#load:
line 34:
E385: search hit BOTTOM without match for; ^[^:]\!^$\|^\s*fini\%[sh]\>
```

vim-templateの`autoload/template.vim`の47行目の以下の行をコメントアウトしたところ上記のエラーがでなくなりました。

```
  silent .;/^[^:]\|^$\|^:\s*fini\%[sh]\>/-1 delete "     
```

https://github.com/thinca/vim-template/blob/master/autoload/template.vim#L47

おそらくここの正規表現っぽい記述がまずいのだと思います。
しかし、自分では理解できませんでした…

もし簡単に直せるようであれば、ご対応いただけませんでしょうか？
難しいようであれば、諦めてテンプレートファイルのコメントを`::`から`REM`にして対応させていただきます。

ご検討どうぞよろしくお願いいたします。

**Comment by thinca** [comment]
1行目に `:finish` と書き、2 行目からテンプレートを書いてください。
詳細は help を読んでください。

**Comment by lamsh** [comment]
すみません…。ヘルプを十分に読めていませんでした…。
ご回答ありがとうございました。
