### ISSUE TITLE
BufNewFile not triggered

### ISSUE THREAD

**Issue by jhessin** [thinca/vim-template#5]
When using this template engine BufNewFile doesn't seem to be triggered. Is there a way to fix that or another hook I can use?

```viml
au BufNewFile,BufRead * setlocal formatoptions-=ro
au BufNewFile,BufRead * set hidden
```

**Comment by thinca** [comment]
I couldn't reproduce it.
Could you tell me the reproduce way with minimal vimrc?

**Comment by jhessin** [comment]
I apologize. The problem was caused by something unrelated to this plugin. 

Thank you. 

- Jim Hessin
